import pytest
import unittest.mock
from bionetgen.simulator.csimulator import CSimWrapper
from bionetgen.core.exc import BNGSimulatorError


def test_set_parameters_error():
    with unittest.mock.patch("bionetgen.simulator.csimulator.ctypes.CDLL"):
        wrapper = CSimWrapper("dummy_lib_path", num_params=3, num_spec_init=2)
        with pytest.raises(BNGSimulatorError) as excinfo:
            wrapper.set_parameters([1.0, 2.0])
        # The exception message generated by BNGSimulatorError based on actual file contents
        assert "Expected 3 parameters, but got 2" in str(excinfo.value)


def test_csimulator_compile_shared_lib():
    from unittest.mock import MagicMock, patch
    import os
    import bionetgen.simulator.csimulator as csim
    from bionetgen.simulator.csimulator import CSimulator

    with patch(
        "bionetgen.simulator.csimulator.bionetgen.bngmodel"
    ) as mock_bngmodel, patch.object(
        csim, "ccompiler", create=True
    ) as mock_ccompiler, patch(
        "bionetgen.simulator.csimulator.bionetgen.run"
    ) as mock_run:

        mock_model = MagicMock()
        mock_model.model_name = "test_model"
        mock_model.parameters = []
        mock_bngmodel.return_value = mock_model

        mock_compiler = MagicMock()
        mock_ccompiler.new_compiler.return_value = mock_compiler

        with patch("bionetgen.simulator.csimulator.CSimWrapper"):
            sim = CSimulator("dummy_file.bngl")

        mock_model.actions.clear_actions.assert_called_once()
        mock_model.actions.add_action.assert_any_call(
            "generate_network", {"overwrite": 1}
        )
        mock_model.actions.add_action.assert_any_call("writeCPYfile", {})

        mock_run.assert_called_once_with(mock_model, out=os.path.abspath(os.getcwd()))

        mock_compiler.compile.assert_called_once_with(
            ["test_model_cvode_py.c"], extra_preargs=["-fPIC"]
        )
        mock_compiler.link_shared_lib.assert_called_once_with(
            ["test_model_cvode_py.o"],
            "test_model_cvode_py",
            libraries=["sundials_cvode", "sundials_nvecserial"],
        )

        assert sim.cfile == os.path.abspath("test_model_cvode_py.c")
        assert sim.obj_file == os.path.abspath("test_model_cvode_py.o")
        assert sim.lib_file == os.path.abspath("libtest_model_cvode_py.so")
