import pytest
import unittest.mock
from bionetgen.simulator.csimulator import CSimWrapper
from bionetgen.core.exc import BNGSimulatorError


def test_set_parameters_error():
    with unittest.mock.patch("bionetgen.simulator.csimulator.ctypes.CDLL"):
        wrapper = CSimWrapper("dummy_lib_path", num_params=3, num_spec_init=2)
        with pytest.raises(BNGSimulatorError) as excinfo:
            wrapper.set_parameters([1.0, 2.0])
        # The exception message generated by BNGSimulatorError based on actual file contents
        assert "Expected 3 parameters, but got 2" in str(excinfo.value)
